# Generated by Django 6.0.1 on 2026-02-12 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_features', '0002_alter_consultantsession_consultant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MockInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('behavioral', 'Behavioral'), ('technical', 'Technical'), ('case_study', 'Case Study')], max_length=20)),
                ('target_role', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_report', models.FileField(blank=True, null=True, upload_to='feedback_reports/')),
                ('completed', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pro_features.consultantslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('pro_plus', 'Pro Plus')], max_length=20)),
                ('mock_interview_quota', models.IntegerField(default=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
