# Generated by Django 6.0.1 on 2026-02-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('free', 'Free User'), ('pro', 'Pro User'), ('pro_plus', 'Pro Plus User'), ('consultant', 'Consultant User'), ('admin', 'Admin User'), ('trainee', 'Trainee User')], default='free', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('pro_plus', 'Pro Plus'), ('consultant', 'Consultant'), ('admin', 'Admin'), ('trainee', 'Trainee')], default='free', max_length=15),
        ),
    ]
