# Generated by Django 6.0.1 on 2026-02-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_consultantmeeting_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('free', 'Free User'), ('pro', 'Pro User'), ('pro_plus', 'Pro Plus User'), ('consultant', 'Consultant User'), ('admin', 'Admin User')], default='free', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('Pro Plan', 'Pro Plan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('pro_plus', 'Pro Plus'), ('consultant', 'Consultant'), ('admin', 'Admin')], default='free', max_length=15),
        ),
    ]
