# Generated by Django 6.0.1 on 2026-02-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_user_type_alter_serviceplan_plan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('pro plan', 'Pro Plan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('pro_plus', 'Pro Plus')], max_length=10),
        ),
    ]
