# Generated by Django 6.0.1 on 2026-02-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_plan_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
