# Generated by Django 6.0.1 on 2026-02-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='amount_paid',
            field=models.CharField(default=0),
        ),
    ]
