# Generated by Django 6.0.1 on 2026-02-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_consultantsession_usernotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultantSession',
        ),
    ]
