# Generated by Django 6.0.1 on 2026-02-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('RM', 'Remote'), ('HY', 'Hybrid'), ('ON', 'Onsite')], default='ON', max_length=2),
        ),
        migrations.AddField(
            model_name='job',
            name='working_schedule',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('IN', 'Internship')], default='FT', max_length=2),
        ),
    ]
